# @package _global_

# This is the main configuration file.
# It composes other files and sets the defaults.

defaults:
  - model: main
  - data: default
  - training: default
  - _self_

# --- W&B Logging ---
wandb:
  log: true
  project: 'shinigami-gpt-v2'
  run_name: 'pretrain-${model.name}' # Dynamic run name

# --- Infrastructure ---
infra:
  compile_model: false

# --- Generation ---
generation:
  temperature: 0.7
  top_k: 100
  speculative_k: 4

# --- DeepSpeed ---
# Path to the DeepSpeed JSON config file
deepspeed_config: "configs/deepspeed/stage2.json"

# Allows hydra to resolve interpolations in this file
hydra:
  run:
    dir: out/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}