name: "Shinigami-Draft-64M"
block_size: 2048
vocab_size: 10000
n_layer: 4
n_head: 4
n_kv_heads: 4
n_embed: 256
dropout: 0.1
untie_weights: true
use_bias: false
sliding_window_size: 4096
moe: {num_experts: 0, num_experts_per_tok: 0}
rope_scaling: {type: "linear", factor: 2.0}
